### ISSUE TITLE
Application crashes while connecting

### ISSUE THREAD

**Issue by KINGSABRI** [USBNinjaRRG/USBNinja-android#1]
Hi, 
The android app crashes while connecting to the usbninja
Note: The password is already being sat. 

Tested on Samsung Note 8

**Comment by jhojgaard** [comment]
Same issue here in Samsung Note 9

**Comment by Chaemelion** [comment]
Same, HTC 10. Here's a trace. https://pastebin.com/sQKgvvTe

**Comment by Mincka** [comment]
Hi,
I had the same issue on a Samsung A8. I ran the Android Studio debugger and found out that it was related to the drawing of a resource.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.RRG.usbninja, PID: 24929
    java.lang.RuntimeException: Canvas: trying to draw too large(137100672bytes) bitmap.
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
        at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
        at android.view.View.getDrawableRenderNode(View.java:20644)
        at android.view.View.drawBackground(View.java:20580)
        at android.view.View.draw(View.java:20360)
        at android.view.View.updateDisplayListIfDirty(View.java:19314)
        at android.view.View.draw(View.java:20092)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at android.view.View.updateDisplayListIfDirty(View.java:19305)
        at android.view.View.draw(View.java:20092)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at android.view.View.updateDisplayListIfDirty(View.java:19305)
        at android.view.View.draw(View.java:20092)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at android.view.View.updateDisplayListIfDirty(View.java:19305)
        at android.view.View.draw(View.java:20092)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at android.view.View.updateDisplayListIfDirty(View.java:19305)
        at android.view.View.draw(View.java:20092)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at android.view.View.draw(View.java:20372)
        at com.android.internal.policy.DecorView.draw(DecorView.java:980)
        at android.view.View.updateDisplayListIfDirty(View.java:19314)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:800)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3501)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3288)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2823)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1785)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7833)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
I've found this SO post with an issue related to the maximum height of pictures.
https://stackoverflow.com/a/43651170/3049282

So, I reduced the size of the `ic_black.png` and `ic_red.png` pictures to 1024px (from 1952px), rebuilt it and voila, it was working fine on my device. I hope it will also help to fix the issue for the HTC 10.

I've made a [pull request](https://github.com/USBNinjaRRG/USBNinja-android/pull/2) with the new images and you can also use this fixed APK in the meantime: [USBninja.zip](https://github.com/USBNinjaRRG/USBNinja-android/files/2798816/USBninja.zip)

Enjoy your USBNinjas! 😄

**Comment by CC0126** [comment]
I've tested your solution, it's very successful. Now I fix the bug on the Github and USBNinja's website. You can download the new apk from the main website. The version is 1.1

**Comment by KINGSABRI** [comment]
I've downloaded the [new APK](https://usbninja.com/help/using-android-phone-to-trigger-payload/) . The fix is confirmed. 

Thank!

**Comment by Mincka** [comment]
@CC0126 : Thanks but sad you didn't merge my pull request. I guess you can also close it now... 😞

**Comment by CC0126** [comment]
Oh,I'm sorry that I didn't notice that...
But now I merged your pull request.
